
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: email-detector-web
    ports:
      - "8000:8000"
    environment:
      - PROJECT_ENV_ID=local
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CACHE_URL=redis://redis:6379/1
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:7-alpine
    container_name: email-detector-redis
    ports:
      - "6379:6379"

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: email-detector-celery
    depends_on:
      - redis
    environment:
      - PROJECT_ENV_ID=local
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CACHE_URL=redis://redis:6379/1
    volumes:
      - .:/app

