# Generated by Django 6.0.2 on 2026-02-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectorresult',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
