# Generated by Django 6.0.2 on 2026-02-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_detectorresult_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectorresult',
            name='input_type',
            field=models.CharField(choices=[('text', 'text'), ('url', 'url'), ('file', 'file')], default='text', max_length=10),
        ),
    ]
